export const RESULT_ACTION_TYPES = {
	FETCH_RESULT_START: 'result/FETCH_RESULT_START',
	FETCH_RESULT_SUCCESS: 'result/FETCH_RESULT_SUCCESS',
	FETCH_RESULT_FAILED: 'result/FETCH_RESULT_FAILED',
};

export const ERROR_ACTION_TYPES = {
	SHOW_ERROR: 'error/HIDE_ERROR',
	HIDE_ERROR: 'error/HIDE_ERROR',
};

export const SIGNIN_ACTION_TYPES = {
	FETCH_SIGNIN_START: 'signin/FETCH_SIGNIN_START',
	FETCH_SIGNIN_SUCCESS: 'signin/FETCH_SIGNIN_SUCCESS',
	FETCH_SIGNIN_FAILED: 'signin/FETCH_SIGNIN_FAILED',
};
